---
title: "Practice Analysis"
output: html_document
date: "2023-06-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}


library(tidyverse)

library(readxl)


```

##data

```{r}

setwd("C:/Users/alext/OneDrive/Documents/data/f1/2023/fp2")




fp2_dat = function(x){
  
  dat = read_xlsx(x)
  
  dat2 = dat %>% mutate(race = x) %>%
                  mutate(seassion = "fp2")
  
}



fp2 = list.files()



fp2_sum = map_dfr(fp2, fp2_dat)


setwd("C:/Users/alext/OneDrive/Documents/data/f1/2023/fp1")




fp1_dat = function(x){
  
  dat = read_xlsx(x)
  
  dat2 = dat %>% mutate(race = x) %>%
                  mutate(seassion = "fp1")
  
}



fp1 = list.files()



fp1_sum = map_dfr(fp1, fp1_dat)

practice_dat = fp1_sum %>% 
                          bind_rows(fp2_sum)

```


## data cleaning

```{r}



clean_dat = practice_dat %>%
                      mutate(lap5 = LapTime *24 *60*60) 



stintal = clean_dat %>% filter(!is.na(PitOutTime)) %>%
                              group_by(DriverNumber) %>%
                                arrange(LapStartDate) %>%
                                mutate(stint2 = 1:n()) %>%
                                select(DriverNumber, PitOutTime, stint2)


min_lap = clean_dat %>% slice_min(lap5) %>%
                              rename(minl = lap5) %>%
                                  select(minl)



 stint_tot = clean_dat %>% group_by(race, seassion, Stint, Driver) %>%
                                        summarise(tot = n())

clean_dat2 = clean_dat %>% left_join(stintal, by = c("DriverNumber", "PitOutTime")) %>%
                                  fill(stint2) %>%
                                    ungroup() %>%
                                      group_by(DriverNumber, stint2) %>%
                                          mutate(stintlap = 1:n()) %>%
                                            bind_cols(min_lap) %>%
                                              mutate(delta = lap5/minl) %>%
                left_join(stint_tot, by = c("race", "seassion", "Stint", "Driver")) %>%
                                                    mutate(lap_fadj = lap5 - ((tot-stintlap)*0.06))
                                                  
                      











```



```{r}

prac_dat = clean_dat2 %>%
                        filter(race == "cagpfp223.xlsx") %>%
                            filter(delta < 1.2)
 





ggplot(prac_dat, aes(x = delta)) + geom_histogram()

ggplot(prac_dat, aes(x = LapNumber, y = lap_fadj)) + geom_point()



```



```{r}


ggplot(prac_dat, aes(x = stintlap, y = lap_fadj)) + geom_point() + facet_wrap(~Compound)










```



```{r}


prac_dat2 = clean_dat2 %>%
                        filter(race == "cagpfp223.xlsx") %>%
                            filter(!is.na(lap5)) %>%
                            mutate(vallap = if_else(delta < 1.2, 1,0))  %>%
                              group_by(Driver, stint2) %>%
                                  summarise(toval = sum(vallap), n = n()) %>%
                                    mutate(per = toval/n)




prac_dat3 = clean_dat2 %>% 
                        left_join(prac_dat2, by = c("Driver", "stint2")) %>%
                            filter(per > 0.75) %>%
                              filter(n > 5)
 






ggplot(prac_dat3, aes(x = stintlap, y = lap_fadj)) + geom_point() + facet_wrap(~Compound)









```



```{r}




medium_tyre = prac_dat3 %>%
                        filter(Compound == "MEDIUM")



ggplot(medium_tyre, aes(x = stintlap, y = lap_fadj)) + geom_point() 








```




```{r}




tyre_model <- function(df) {
  lm(lap5 ~ stintlap, data = df)
}


med_tyre_sum = medium_tyre %>% group_by(Driver, stint2) %>%
                                        nest() %>%
                                          mutate(mods = map(data, tyre_model))    





```





```{r}


med_tyre_perf = function(){
  
  tyre_dat = med_tyre_sum %>% filter(Driver == "VER")
  
  
  mod = lm(laps ~ stintl, )
  
  
  
  
}








`````